# .sprint.yml — Optional project-level configuration for TeamClaude
# Place this file in your project root. Auto-detection is the default.

verification:
  # Commands to verify code quality. Detected automatically from lockfile + package.json.
  # type_check: "pnpm type-check"
  # test: "pnpm test --run"

agents:
  # Default model for all sprint agents
  model: sonnet

sprint:
  # Maximum review rounds before escalating a task
  max_review_rounds: 3

server:
  # Visualization server port
  port: 3456
