name: Feature request
description: Suggest an idea for TeamClaude
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? Is it related to something frustrating?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the feature you'd like.
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Which component does this affect?
      options:
        - dashboard
        - server
        - CLI
        - agent prompts
        - other
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
